In [18]:
import numpy as np

In [2]:
def calculator(list_of_numbers):
    result = 0
    for number in list_of_numbers:
        if type(number) == int:
            result = result + number
        else:
            print('ERROR: Wait, a calculator needs numbers, what are you doing?')
    print(f'The result is {result}')  

In [3]:
numbers = [1,2,3,4,5]

In [4]:
calculator(numbers)

The result is 15


In [6]:
my_first_array = numpy.array(numbers)

In [7]:
my_first_array

array([1, 2, 3, 4, 5])

In [8]:
my_first_array[0]

1

In [9]:
my_first_array.shape

(5,)

In [10]:
my_first_array.sum()

15

In [19]:
def calculator(array_of_numbers, operation):
    result = operation(array_of_numbers)
    return result

In [22]:
calculator(my_first_array, m)

3.0

In [21]:
from numpy import mean as m

In [23]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]


In [25]:
mat = np.array(matrix)

In [26]:
mat.shape

(3, 3)

In [31]:
random_matrix = np.random.random((3,3))
random_matrix


array([[0.83110216, 0.07512639, 0.02781128],
       [0.1368535 , 0.16787033, 0.02875025],
       [0.49771922, 0.95941451, 0.91760249]])

In [32]:
random_matrix.sum()

3.642250124590883

In [36]:
random_matrix.std(axis=1)

array([0.36802994, 0.05963104, 0.20849001])

In [34]:
random_matrix.sum(axis=0)

array([1.46567488, 1.20241123, 0.97416402])

In [38]:
random_matrix_1 = np.random.random((3,3))
random_matrix_2 = np.random.random((3,3))

In [39]:
np.add(random_matrix_1, random_matrix_2)

array([[0.90396912, 1.43015393, 1.20915647],
       [0.31305462, 1.13113546, 0.59547843],
       [1.21328105, 1.17069781, 1.30702958]])

In [41]:
np.subtract(random_matrix_1, random_matrix_2)

array([[-0.74693307,  0.05920388, -0.60278075],
       [ 0.1738103 , -0.53769788, -0.55211263],
       [-0.76253204, -0.08282088,  0.29852361]])

In [43]:
np.multiply(random_matrix_1, random_matrix_2)

array([[0.06481279, 0.51045879, 0.27467869],
       [0.01694829, 0.24758711, 0.01244155],
       [0.22264895, 0.34091852, 0.40480249]])

In [44]:
random_matrix_1

array([[0.07851802, 0.74467891, 0.30318786],
       [0.24343246, 0.29671879, 0.0216829 ],
       [0.22537451, 0.54393847, 0.80277659]])

In [45]:
random_matrix_2

array([[0.8254511 , 0.68547502, 0.90596861],
       [0.06962216, 0.83441667, 0.57379553],
       [0.98790655, 0.62675935, 0.50425298]])

In [46]:
matrix_2 = np.array([[0,2,3],[4,5,6],[7,8,9]])


In [47]:
np.divide(random_matrix_2, matrix_2)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[       inf, 0.34273751, 0.30198954],
       [0.01740554, 0.16688333, 0.09563259],
       [0.14112951, 0.07834492, 0.05602811]])

In [48]:
3/0

ZeroDivisionError: division by zero

In [49]:
np.divide(0,0)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [50]:
np.inf

inf

In [51]:
x = np.inf

In [52]:
x

inf

In [54]:
np.isinf(x)

True

In [55]:
type(x)

float

In [57]:
x > 3.0

True

In [59]:
np.inf < 3.0

False

In [60]:
range(x)

TypeError: 'float' object cannot be interpreted as an integer

In [61]:
int(x)

OverflowError: cannot convert float infinity to integer